### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by mikeal** [nodejs/code-and-learn#1]
Let's discuss how we want to deliver this program to achieve our goes.
- What is the minimum length of a Code + Learn?
- What are some events that we can integrate with?

**Comment by mikeal** [comment]
@wraithan @piscisaureus I remember you both had a lot of great ideas during the summit.

**Comment by jasnell** [comment]
Step one should be determining the agenda/goals and figuring out what parts of that the current nodeschool curriculum does not cover.

**Comment by mikeal** [comment]
@jasnell that's addressed in the README :)

**Comment by jasnell** [comment]
Sigh. It helps if I RTFR, eh?

**Comment by Trott** [comment]
Putting together an outline for a draft syllabus would probably inform the answers to both questions.

Is the idea that different Code + Learn events would lead towards different parts of the code base? Like, maybe some C++ stuff using libuv or whatever one time, and streams the next time, etc. Or is it more like different attendees at each event end up in different parts of the code base depending on their interest and the expertise of the mentors in attendance? TBD?

EDIT: I see you answered this question [here](https://github.com/nodejs/code-and-learn/issues/2#issuecomment-130731892).

**Comment by mikeal** [comment]
What we can accomplish in each of these is fairly dependent on the contributors we get. For instance, with Trevor at Waterford and Ben at Berlin each is going to look a bit different, and probably wildly different from Dublin and London where we might only have website contributors.

Also, we want to get people diving into real work and issues, which change week to week. I think that the mentors in each workshop will need a list of stuff to produce for the workshop:
- Quick introduction to the code base and dev environment for the area they are targeting.
- List of open issues and tasks to tackle.

Perhaps the only thing to do in _every_ session is to start off with everyone sending a PR to this repo adding a file about themselves to a directory for the workshop. That'll help make sure everyone has a GitHub account and can PR and it also helps us track who has been in which session.

**Comment by Trott** [comment]
I'm sure this is part of the plan, but just to make it explicit: It would be great if there was sufficient direction provided by this repo such that no specific individual (e.g., @mikeal) needs to be there. Just as long as there's a critical mass of collaborators (three? one?)... I suppose a checklist or something like that can be created after two or three of the events have happened and there's a decent idea of what works well and what doesn't work well.

**Comment by iancrowther** [comment]
thats a good call - de-centralise things

**Comment by mikeal** [comment]
That's the eventual goal. I'm going to run a few of these in September and
come back with what we've learned and write it all up. At that point it
should be easy for anyone to run one.

**Comment by Trott** [comment]
Additional idea: Have collaborators do a run-through using other collaborators as the learners. This will:
- hopefully identify issues before they affect "real" learners
- spread knowledge around among existing collaborators

I would love to learn more about libuv etc. through a process like this.

Might only be feasible for areas that have a critical mass of collaborators already, unless we break the must-be-in-meatspace requirement for the run-throughs.

**Comment by iancrowther** [comment]
@mikeal will you be putting together the "How to run a code-and-learn" file once you have completed your trials.

**Comment by mikeal** [comment]
Yup, the first few are each very different so we're going to see how they go and then build up a document that should help more people run and sustain them.

**Comment by iancrowther** [comment]
great

**Comment by Trott** [comment]
I think it's safe to close this issue at this point, but if anyone disagrees, please feel free to comment saying so.
