### ISSUE TITLE
September Events

### ISSUE THREAD

**Issue by mikeal** [nodejs/code-and-learn#2]
There's a number of existing events in Europe in September that we should target. Additionally, I'll be in Europe the entire month and can help put together the logistics of each event.
- FutureJS, Barcelona (September 4-5)
- NodeConf.eu, Waterford, Ireland (September 8th)
- Dublin (I'll be here a few days after NodeConf.eu)
- London (I could easily go to London after Dublin)
- Web Tech Fest Berlin http://wwwtf.berlin/

What other contributors will be in these areas these dates?

**Comment by jasnell** [comment]
I'll be in Waterford for NodeConf.eu. That said, IBM is already leading two of the workshops and we have full agendas for those already. Not sure if the agenda is going to leave much room for more.

**Comment by iancrowther** [comment]
@mikeal put me down for London.

**Comment by mikeal** [comment]
@iancrowther any thoughts about venue?

**Comment by iancrowther** [comment]
i have a few, it depends on what capacity your after?

start small with 30-50 and venues are good to go.  more than that we need to make some calls but I have a list from my LNUG searches.

I need more info really.  is this a big bang, big PR job? do we want 100 in the room?

we need to be able to get enough experienced heads in the room to actually teach the materials

**Comment by mikeal** [comment]
@iancrowther less than 50 for sure :)

**Comment by iancrowther** [comment]
ok so we need some materials pronto hey.  anything in the works?

**Comment by iancrowther** [comment]
can we leverage some of the going native bits from nodeschool?

**Comment by iancrowther** [comment]
@mikeal ok so I have a venue primed.

do we have a landing page so I can tkt and PR?

**Comment by iancrowther** [comment]
anyone used any cool pairing tools? Atom maybe?  

we could get funky and do a cross border pairing session?

**Comment by mikeal** [comment]
> materials

So, the idea here is that we get people diving in to areas that are not already widely understood. That sort of excludes areas with a nodeschool tutorial already written about them.

Instead, I'm pulling in all the contributors that can make it and asking them to write up issues and find things people can work on with a little guidance. The mentors will be providing that guidance in person on a one on one basis.

This means that what gets covered will be heavily dependent on who is there. If I'm the only mentor there we're gonna do a lot of work on the website! :)

> website

I'll get to work on this ASAP.

**Comment by iancrowther** [comment]
1st draft logo for London

https://files.gitter.im/maxwellito/xlBW/thumb/Screen-Shot-2015-08-20-at-22.03.17.png

**Comment by mikeal** [comment]
London! Ya'll are amazing!

**Comment by mikeal** [comment]
So, the board meeting is pushed back a week so I'm going to go ahead and move forward this week making these happen. The trick is that I can't commit to spending any money whatsoever until the board approves.

Let's get the word out about London and try to track down mentors.

@iancrowther do you think the best way to capture this is to create a new issue here for the London even and have mentors just signup? after a week of that maybe switch to signing up mentors via tito.

Side note: any of the London crew going to make it to NodeConf.eu in Waterford?

**Comment by iancrowther** [comment]
@mikeal - A london thread for sure, noise sucks.

I'll announce tomorrow at LNUG and see 

a) who wants to come 
b) who wants to help 
c) who can mentor

We will really need to push for mentors so a sign up form alone won't cut it.  we need to tweet and direct email so lets put a list of names together on a gsheet and reach out.  we could just '@' them on the github thread if thats easier.

No worries on the meeting, just push on.

Can you put up a GH page by tomorrow evening? super basic so we have somewhere to send traffic.  Im in back to back meetings tomorrow so dont have the capacity.

I'd get ti.to up asap and out into the wild, eg this week ath the latest.  I can do that as I have the venue details.

.eu! I just cant get to it unless cian hooks me up with a unicorn tkt, really really want too!

**Comment by mikeal** [comment]
@iancrowther for mentors maybe we should just track down any nearby
contributors and push them to sign up? I doubt there are that many, but we
don't need that many, this isn't NodeSchool :) In fact, the kinds of people
who usually mentor a NodeSchool might be great candidates to attend this :)

**Comment by iancrowther** [comment]
totally agree - i have a few folks in mind

**Comment by iancrowther** [comment]
Feedback

- Intro to the focus area was really essentail, in our case the website
- Paired programming was great for getting to know people
- We just about had enough issues specified to work on

Next time
- Delegate lead mentor who will drive the area of focus
- Define a list of issues that can be worked on during the event appropraite from beginner to advanced.

**Comment by iancrowther** [comment]
Thanks to everyone who was involved with this event.

**Comment by iancrowther** [comment]
Closed the wrong issue! sorry

**Comment by iancrowther** [comment]
@mikeal - happy to close now?

**Comment by mikeal** [comment]
Yup, closing. Will writeup a redux of what we learned later.
