### ISSUE TITLE
London - Saturday 12th September 2015 

### ISSUE THREAD

**Issue by iancrowther** [nodejs/code-and-learn#4]
A seperate thread for event info and mentor signup

**Comment by iancrowther** [comment]
https://files.gitter.im/maxwellito/xlBW/thumb/Screen-Shot-2015-08-20-at-22.03.17.png

**Comment by iancrowther** [comment]
@mikeal - any news?

**Comment by mikeal** [comment]
We are a go! :)

**Comment by maxwellito** [comment]
![lnug_logo_final](https://cloud.githubusercontent.com/assets/1097232/9662683/71acf8b6-5258-11e5-9e16-cea671dc68cb.png)
That is the final! :) Much better

**Comment by iancrowther** [comment]
https://ti.to/code-and-learn/london-september-2015

**Comment by iancrowther** [comment]
i was going to make a landing page but was a bit unsure.. maybe we can do on sat

**Comment by iancrowther** [comment]
Feedback
- Intro to the focus area was really essentail, in our case the website
- Paired programming was great for getting to know people
- We just about had enough issues specified to work on

Next time
- Delegate lead mentor who will drive the area of focus
- Define a list of issues that can be worked on during the event appropraite from beginner to advanced.

**Comment by iancrowther** [comment]
Thanks to everyone who was involved with this event.
