### ISSUE TITLE
Chapter organisation

### ISSUE THREAD

**Issue by iancrowther** [nodejs/code-and-learn#40]
Will each chapter be listed on `nodejs.org/get-involved/events/code-and-learn`

**Comment by iancrowther** [comment]
this maybe a q for the new.nodejs.org repo, but the code-and-learn page does not exist yet :-)

**Comment by iancrowther** [comment]
currently https://nodejs.org/en/get-involved/code-and-learn/ goes to https://ti.to/code-and-learn.

We could do with a dedicated page that highlights the next event and maybe filters by chapter.

**Comment by Trott** [comment]
I think it's safe to close this issue at this point, but if anyone disagrees, please feel free to comment saying so. In the meantime, I'll see about getting the Code + Learn page updated with July details if they're known.
