### ISSUE TITLE
London - Next Event - November 28th 2015

### ISSUE THREAD

**Issue by iancrowther** [nodejs/code-and-learn#51]
We are launching a new event on November 28th in London called the Node Jamboree. We're going to run a 4 track meet up in the morning, followed by a code party in the afternoon / evening. 

The tracks are: 
- Nodeschool 
- Nodebots 
- Meteor 
- Code and Learn 

@mikeal @fhemberger - when can we jump on a call to start putting a priority list together for code and learn.

Anyone from the webwg fancy coming along? Will be a fun day with lots of onboarding.

**Comment by fhemberger** [comment]
At the moment I don't have any topics for the website to work on.

But it would really be super-super-awesome to have a script converting the old legacy documentation into something similar to the new docs. At the moment, the old documentation is simply a complete mirror of the entire website at that point in time, so we have to maintain assets and redirects. A good start would be to have the docs for latest-v0.10.x and latest-v0.12.x.
- Get content from `#content-wrap` with [cheerio](https://www.npmjs.com/package/cheerio)
- Put it in the new template:

``` html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Node.js v##version## Manual &amp; Documentation</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic">
    <link rel="stylesheet" href="assets/style.css">
    <link rel="stylesheet" href="assets/sh.css">
    <link rel="canonical" href="https://nodejs.org/api/##generated##.html">
</head>
<body class="alt apidoc" id="api-section-##generated##">

    ##content##
    <div id="footer">
    </div>

    <script src="assets/sh_main.js"></script>
    <script src="assets/sh_javascript.min.js"></script>
    <script>highlight(undefined, undefined, 'pre');</script>
</body>
</html>
```
- Replace content of #column2 on all pages with index.html#apicontent

@mikeal @rvagg @nodejs/website What do you think about this?

**Comment by mikeal** [comment]
also the new knowledge base needs a ton of work before it is linked to on the main page.

**Comment by iancrowther** [comment]
ok ill have a think about this over the weekend
