### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by williamkapke** [nodejs/code-and-learn#54]
I have been really looking forward to seeing this progress.. but it seems to have stalled (about 6 months now)...? 

The [Code + Learn](https://nodejs.org/en/get-involved/code-and-learn/) section of the website under [Get Involved](https://nodejs.org/en/get-involved/) is a bit stale now. The link to https://ti.to/code-and-learn only shows 1 past event a long time ago. As anyone reading this knows... Node.js involvement isn't **stale** _at all_! If not updated, maybe just removed for now?

**Comment by iancrowther** [comment]
hey - this is very much on my radar and am aiming to run an event in march

**Comment by williamkapke** [comment]
Ok. I'll keep a watch on this repo for more info then.

**Comment by williamkapke** [comment]
Progress has been made! New events on the way!

I've opened an issue on the nodejs.org repo to update the stale info on website. 
https://github.com/nodejs/nodejs.org/issues/796
