### ISSUE TITLE
Merge with NodeTodo

### ISSUE THREAD

**Issue by mikeal** [nodejs/code-and-learn#57]
This effort is pretty awesome and has a less confusing name than this effort http://nodetodo.org/

**Comment by Trott** [comment]
Node Todo is still pretty new (we've had about 5 events and so far have helped about 25 people get their first PRs in). It was envisioned specifically as independent from the Foundation and the project. It's closer to the NodeSchool model: Oh, hey, here's what we do, and if you want to do this in your location, please do!

So, you can basically just create an event and declare that it's Node Todo. I do ask that anything labeled Node Todo be free, open to the public, and use a reasonable Code of Conduct. (I use the JSConf CoC.) Also, people running a Node Todo should be people who have contributed code to Node.js. And I'd love to post other people's Node Todo events on the website.

**Comment by mikeal** [comment]
Node Todo seems a lot more scalable that what we've been doing here and I like that it's more in the NodeSchool vein.

I'd prefer to deprecate this repo and pour any funding and other resources we had been spending on this into Node Todo :)

**Comment by hackygolucky** [comment]
I'm happy to help where I can with this(pointing resources this way, alotting some time, pitching in where my help is useful). Sounds like a rad way to concentrate community energy.

**Comment by hackygolucky** [comment]
@Trott @addaleax Any further thoughts on this? I know Code and Learn takes a lot of explaining when I'm evangelizing it, just from the perspective of folks thinking it's doing more than teaching How to contribute and code especially in Core. 

The internal team was also asking about branding--is there a logo for either Code and Learn or NodeToDo? They have the awesome videos from Code and Learn in Austin about ready to go.

**Comment by Trott** [comment]
@hackygolucky No further thoughts on this other than: "Code and Learn" implies the wrong thing and we would do well to change the name to *something* else...

**Comment by addaleax** [comment]
Also, no, there’s no logo that I’d be aware of

**Comment by Trott** [comment]
Seems like we're sticking with "Code + Learn" for now, for better or for worse. Maybe we can consider a re-brand in 2018, but right now, we have three more events lined up as "Code + Learn" so I imagine we're sticking with it for the rest of the year at least.

I think it's safe to close this issue at this point, but if anyone disagrees, please feel free to comment saying so.
