### ISSUE TITLE
Code And Learn at Node Interactive in Austin

### ISSUE THREAD

**Issue by addaleax** [nodejs/code-and-learn#59]
Time: December 1, 9 am – 12 am (3 pm – 6 pm UTC).

Todo:
- [ ] Gather and pre-review tasks for participants to address
- [ ] Prepare storage medium (Network storage seems to be the best idea) for downloading a fresh clone of the core repository + eventually needed compilers
- [ ] Get estimates for mentor/attendee numbers
- [ ] Solicit off-site collaborators who can start reviewing PRs while the event is happening
- [ ] Write a proper description of the event for the Agenda

**Comment by addaleax** [comment]
@nodejs/collaborators: Who of you is going to be at NI NA and is able to help with mentoring Code & Learn attendees? Are some of you likely going to be able to review PRs as they are being opened?

**Comment by imyller** [comment]
I'm available for reviewing & mentoring PRs remotely.

I suggest that new (temporary) Github Project is opened for grouping Austion C&L session PRs and special attention is given for those to make it a pleasant experience for participants.

**Comment by bengl** [comment]
If I'm at NINA (most likely), I'm in. If not, happy to review.

**Comment by Trott** [comment]
I'll be there!

**Comment by evanlucas** [comment]
I'll be there and would love to help!

**Comment by williamkapke** [comment]
I'll be there in a supportive role (like I did in Amsterdam).

**Comment by MylesBorins** [comment]
o/

**Comment by bmeck** [comment]
I can be there to help in person :)

**Comment by jasnell** [comment]
I'll be there for sure.

**Comment by mcollina** [comment]
I'll be there.

A couple of notes. I think we should come up with more substantial "good-first-contributions", so all mentors should probably engage in creating/tagging some issues _before_ the event.
A massive amount of var -> const is not 100% what it needs.

I think we should also stress the fact that in OSS we triple-check each other work, and it takes a while for a contribution to land. And they need to stick with it, and follow it through till its landed.
There is the misconception that their task was _just_ sending a PR. The amount of back-and-forth and change needed is quite high.

Regarding the fresh checkout, a couple of USB sticks and instructions can do wonders. We can also send them instructions on how to do a checkout _before_ the event.. :)

**Comment by lrlna** [comment]
Ooo! Y'all are doing another one in Austin! I am gonna come again then ^_^

**Comment by sam-github** [comment]
I'll be there, I can help.

**Comment by addaleax** [comment]
Okay I’m closing this in favour of @hackygolucky’s #60, that seems a bit more organized, but I’ll take the liberty to add people who raised their hand for mentoring here over there :)

**Comment by addaleax** [comment]
(Please indicate the OS combinations you’d be able to help with over there!)
