### ISSUE TITLE
Set git fullname and email

### ISSUE THREAD

**Issue by jasnell** [nodejs/code-and-learn#63]
@addaleax / @trott -- In the instructions for getting started, it would be helpful to include the instructions showing how to set a user's full name and email in their git configuration.

**Comment by addaleax** [comment]
https://github.com/addaleax/code-and-learn-2016/commit/61cdbc41047b2284c6bcabc8766622320b00b097 – works for you? We can try to work on an “official” deck of slides if that makes sense

**Comment by jasnell** [comment]
Yes! That's exact what I'm looking for.

**Comment by Trott** [comment]
Cool. I'm going to do something similar at http://nodetodo.org/getting-started/

**Comment by Trott** [comment]
@addaleax I used your text/example with small modifications. If that's OK and no attribution is needed, awesome. If that's Not Cool and there should be some attribution, let me know and it will force me to create an authors file or prior art or something, which I probably should be doing anyway. :-P

**Comment by addaleax** [comment]
@Trott That’s perfectly fine, do whatever you want with it =) (Also, the example commands are taken from core’s CONTRIBUTING.md, so… credit for those would go to Ben)

**Comment by Trott** [comment]
I think it's safe to close this issue at this point, but if anyone disagrees, please feel free to comment saying so.
