### ISSUE TITLE
Upcoming Code-and-Learns?

### ISSUE THREAD

**Issue by joshgav** [nodejs/code-and-learn#64]
@Trott @addaleax what's the best way to find out about upcoming code-and-learns? Thanks!

**Comment by mikeal** [comment]
Here's what I have from the budget allocation:

 * 2 international events: NodeConf EU, JSConf.CN
 * Node Interactive 2017
 * 1 SF Code and Learn
 * Budget allocated to send Rich and Anna to all events.

**Comment by Trott** [comment]
SF-area (Oakland, to be specific) event specifically targeting URMs for attendance is scheduled for Saturday, April 22. Details should be announced/publicized soon-ish. Paging @hackygolucky. Should be on the website soon-ish I think. 

In the meantime, I'd love it if any @nodejs/collaborators who think they can make it to the event (to help folks working on getting their first pull request into Node.js) would comment here. The number of attendees we can handle is going to depend on how many mentors we can gather.

The other three events this year: Node Interactive is in early October, NodeConf EU is in early November, and (as far as I am aware) JSConf.CN has not yet been scheduled. (Anyone know anything about JSConf.CN? Is it possible it's not happening at all this year or something like that?)

**Comment by addaleax** [comment]
> (Anyone know anything about JSConf.CN? Is it possible it's not happening at all this year or something like that?)

maybe somebody from @nodejs/nodejs-cn knows?

**Comment by fengmk2** [comment]
JSConf.CN can contact @xeodou and @goddyZhao

**Comment by xeodou** [comment]
@mikeal @Trott The JSConf.cn this year, it's on the way, it will happen around July.  And the `code and learn` seems a very cool project, i read the docs but still didn't get into it. Can you guys share more details for me or point out the materials that i can find it out ? If there is an event already happened before can you share more experiences with us, then we can make it happen in China.

**Comment by addaleax** [comment]
@xeodou Basically, we gather a couple mentors who are active Node core contributors and a number of attendees in a room and guide them to making their first contribution(s) to the Node core codebase itself! So far the events we’ve held at conferences (the ones I was part of were at the Node Interactive confs last year) were a pretty big success I’d say.

There’s also a really cool promo video coming out soon, I’ll send you the link per email :)

**Comment by xeodou** [comment]
That's awesome , thanks @addaleax   
I also found the ticket that @hackygolucky host the event at Austin last year. It's a good starter for me look into how it works.

**Comment by joyeecheung** [comment]
If a code-and-learn at JSConf.CN is gonna happen I will be available as a mentor :) I am based in Hangzhou and our team is probably going to be there this year. I am going to notify other collaborators based in China that I know.

**Comment by joyeecheung** [comment]
Also I have participated in a previous code-and-learn session (in Austin) so I more-or-less know how it works. @xeodou You can contact me if you want to know about the details.

**Comment by pmq20** [comment]
@joyeecheung Feel excited about the news. Please definitely count me in if it was going to happen at JSConf CN this year :-)

**Comment by Trott** [comment]
For the event on Saturday April 22 in Oakland, so far I only count 3 definite mentors (@addaleax, @bengl, and me) + 1 who might be able to make it, so 3-4 mentors so far.

I think we probably shouldn't do an attendee-to-mentor ratio more than 5:1, so right now we're talking about being able to handle just 15-20 people.

I think the space can hold 60 or 75 people, so ideal is probably about 10 or 12 mentors to 50 or 60 attendees. 

There's definitely room for more @nodejs/collaborators to volunteer!  (Hint, hint!)

**Comment by hackygolucky** [comment]
So, I've reached out to a number of orgs for the SF Code + Learn and I'm waiting to hear back. We've got a registration form created and has been shared with said orgs, but as mentioned above we'll certainly need a gaggle of mentors! Do y'all mind if I open an issue for each separate Code + Learn we are aiming for so we can coordinate individually in each? I know some organization/logistics spans all of them, but seeking mentors is more specific to each event. Or should I create a mentor form too? It was super helpful with NodeTogether. cc @addaleax @Trott

**Comment by addaleax** [comment]
> Do y'all mind if I open an issue for each separate Code + Learn we are aiming for so we can coordinate individually in each?

Sounds good!

> Or should I create a mentor form too?

I don’t know in what ways that helped for NodeTogether (and I’d be curious to hear), but maybe things are different for Code & Learn – the pool of mentors to draw from is overseeable in size and they don’t really need to prepare much in advance.

**Comment by xeodou** [comment]
That's awesome. @joyeecheung  @pmq20   
I'll push hard to make it happen in JSConf CN this year, i'll write back when i got any updates.

**Comment by yorkie** [comment]
Count me in, I'm excited with this in China :)

**Comment by joyeecheung** [comment]
@xeodou Just saw http://www.bagevent.com/event/455850, looks like JSConf China will be hosted in Shanghai, 15-16 July, right? That's good news since most Chinese collaborators I know live in Shanghai or Hangzhou (1h of train away) :D

**Comment by xeodou** [comment]
Hi  @joyeecheung   

Congrats dude!! You found it, we even didn't ready to lunch it. Yep, it will happen in Shanghai July 15-16. After 5 years, we turn back to Shanghai again, i will be more exciting this year, we would like see more Node.JS guru give some interesting talk.  🚀

**Comment by Trott** [comment]
Hooray!

@xeodou FYI, the YouTube link on the bagevent.com page for the event doesn't work because there is a trailing `)`. 

It's neat to see some folks who I only know from GitHub at a podium and speaking in those videos.
:-D

**Comment by xeodou** [comment]
Thanks @Trott , fixed.
We are not official publish yet, so i believe there are lots of issue out there, thank you for point it out. ;)

**Comment by joyeecheung** [comment]
@xeodou Awesome! \o/ (and uh...I am not a dude :p)

**Comment by TimothyGu** [comment]
I might be able to attend a C&L in Shanghai if it is in July.

**Comment by Trott** [comment]
JSConf.cn Code + Learn discussion at https://github.com/nodejs/code-and-learn/issues/68. I'm going to close this issue, but if anyone thinks that's not the right thing to do, feel free to comment or re-open.
