### ISSUE TITLE
Mentors for April 22 in Oakland, California (US)

### ISSUE THREAD

**Issue by Trott** [nodejs/code-and-learn#65]
Hi, @nodejs/collaborators! We're having a Code & Learn (help people get their first contribution into Node.js) on Saturday, April 22 in Oakland, California (US).

By my figuring, we'd be best served having about 12 mentors.

Right now, we have 3 definite mentors and 1 probable mentor.

So... if you can get to Oakland that day, and you want to help new folks get going contributing to Node.js core, and (as a bonus) get to spend a little time with other contributors, please leave a comment here. Thanks!

- [x] @addaleax 
- [x] @bengl 
- [x] @Trott 
- [x] @jasnell
- [x] @JoeDoyle23
- [ ] you?
- [ ] you? 
- [ ] you? 
- [ ] you? 
- [ ] you? 
- [ ] you? 
- [ ] you?

**Comment by Trott** [comment]
Ping @JoeDoyle23

**Comment by JoeDoyle23** [comment]
What time are we looking to hold this? I have a previous commitment in the late afternoon, but should be able to help out earlier in the day.

**Comment by Trott** [comment]
I believe the start time is 10AM. (Right, @hackygolucky?)

**Comment by JoeDoyle23** [comment]
Timing works. I'm in!

**Comment by ofrobots** [comment]
Apologies – I won't be able to join – family stuff in the morning / afternoon.

**Comment by williamkapke** [comment]
Dropping this signup link here in case someone else comes here looking for it:
https://docs.google.com/forms/d/e/1FAIpQLSdxMaLiEZ58fVtI0QS1On6mAGjLFQ2tgr35pwCdFVpB34j_Dg/viewform

**Comment by hackygolucky** [comment]
10am-2pm, drinks and lunch included. Emailing all of the attendees and y'all now as a reminder!

**Comment by ChALkeR** [comment]
_Since I got pinged on this_ ;-) — is there anything more that should be done on the issue, or could the issue be closed?

Judging from the dates, the event has passed.

**Comment by addaleax** [comment]
Thanks for the reminder! Yes, this can be closed now.
