### ISSUE TITLE
Things needed for most Code + Learn

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/code-and-learn#66]
We noticed at today's Code+Learn in Oakland that we've been lucky when folks had one or more of these things, and it'd be great to have them consistently:
- thumb drive with node.js install
- thumb drive with xcode
- Code + Learn sign(design and print, can be shipped wherever and budget has already been approved)

**Comment by Fishrock123** [comment]
Not everyone is too fond of pluging in USB drives though - would it still be a better plan to have a Wifi router and like, something to serve those over a local network in a better way?

I understand USB drives can be a start and are better than nothing but I'd certainly prefer do it in better ways.

**Comment by nebrius** [comment]
With the router approach, we could always use something inexpensive like a Raspberry Pi for hosting files. An advantage of the network sharing approach is that there isn't the physical item bottleneck, i.e. multiple people can download from the network at the same time, but not from a physical USB device.

**Comment by bengl** [comment]
For the node source tree: one person's laptop with a git repo made available to the network with something like `git daemon` should suffice. However, I've seen cases where the local facility-provided WiFi doesn't allow connections between devices connected to the AP. A portable AP (perhaps even just someone's smartphone?) could probably solve this.

Could we have a set of "recommended prerequisites to download"?

**Comment by joyeecheung** [comment]
"recommended prerequisites to download" that I have listed in https://github.com/nodejs/code-and-learn/issues/68#issuecomment-315036991 for code-and-learn in Shanghai, I believe this worked good enough:

1. Install compilers and build tools
    * Linux
        * gcc and g++ 4.9.4 or newer versions（or clang and clang++ 3.4.2 or newer versions)
        * GNU Make 3.81 or newer versions
        * Python 2.6 or 2.7
    * Mac:
        * [Xcode](https://developer.apple.com/xcode/) and the latest Xcode Command Line Tools (`xcode-select --install`)
    * Windows
        * [Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools), or [Visual Studio 2015 Update 3 or later](https://www.visualstudio.com/downloads/), or [Visual Studio 2017](https://www.visualstudio.com/downloads/)
        * Python 2.6 or 2.7
2. Clone the [nodejs/node repo](https://github.com/nodejs/node), if you don't need the git history, use `git clone --depth=1` to speed up the download

(See [BUILDING.md](https://github.com/nodejs/node/blob/master/BUILDING.md) for details)

BTW I have observed that cloning the source code with `--depth=1` costs about 100MB+ of transfer and Xcode costs about 5GB...

**Comment by Trott** [comment]
I think this can be closed, but if anyone thinks that's wrong and there's still stuff to work out on this, feel free to comment or re-open!
