### ISSUE TITLE
JSConf.cn Code + Learn planning and logistics

### ISSUE THREAD

**Issue by Trott** [nodejs/code-and-learn#68]
Let's figure out how Code + Learn in Shanghai is going to work!

Based on other Code + Learn events,  we should try to schedule it for at least 3 hours. 4 hours is better. If we can schedule for 5 hours, that would be great but I wouldn't expect people to stay the entire time.

* JSConf.cn is July 15 and 16. (http://www.bagevent.com/event/455850)
  * Will Code + Learn be on one of those days? The day before? The day after?
  * Will it be part of the JSConf.cn program? Or separate?
  * Will we be able to have it take place in the same location? If not, where might be available?

* Attendees
  * How many will the space accommodate?
  * How do we promote/handle registration?

* Travel/Mentors
  * We'll want about one mentor for each 5 attendees. 
  * @Trott (that's me!) does not speak Chinese. How much does that matter? (If it's what makes the most sense, I'm fine with helping in the preparation of issues, being available to label PRs as they come in and run them through CI, etc., but not actually being there. I'd love to go to Shanghai, but I wouldn't want the Foundation to spend the money to send me if I'm not going to be particularly effective there.)

I'm sure there are a dozen other things we'll have to consider, but just to get started, there's what I'm thinking about right now.

/cc @xeodou @HackyGoLucky @addaleax @joyeecheung @pmq20 @yorkie @TimothyGu

Mentors:

- [x] @addaleax 
- [x] @Trott
- [x] @joyeecheung 
- [x] @DavidCai1993 
- [x] @TimothyGu 
- [x]  @bengl 
- [x] @JacksonTian 
- [x] @XadillaX
- [x] @yorkie
- [ ] you?
- [ ] you?

**Comment by joyeecheung** [comment]
July 15 and 16 are weekends so if C+L happens on those days we would be able to attract more people (and people who are not going to attend JSConf but want to attend C+L). That said we can still do it on the day before/after JSConf if it would distract the JSConf crowd too much, though the turnout would probably be lower if the C+L happens on weekdays.

I think it's OK if @Trott doesn't speak Chinese, there were many speakers giving English talks at JSConf China before, maybe there will be some this year too. At least part of the attendees should be able to communicate in English, some of them might even be more comfortable speaking English.

/cc @DavidCai1993 because if I remember correctly you are based in Shanghai? Would you be interested in mentoring in this C+L?

**Comment by DavidCai1111** [comment]
@joyeecheung Sure, count me in :=)

**Comment by TimothyGu** [comment]
I will be in Shanghai during the entirety of July as well, so let me know if there is anything I can help with. I do speak both Mandarin and English (and FWIW I understand [Shanghainese](https://en.wikipedia.org/wiki/Shanghainese)), though I'm more confident in English than I am in Mandarin these days, especially when it comes to programming terms.

**Comment by Trott** [comment]
I've added a mentor list to the original post above.

@TimothyGu Considering we both live in California, it will be somewhat strange to meet you for the first time on an entirely different continent. Looking forward to it.

**Comment by xeodou** [comment]
Hey Guys

I can give some updates from JSConf China side. Yeah, we are very happy the C+L can be part of the program. The venue we booked now doesn't have too much space for a workshop, but we already check another meeting room at the same location, it should be able fit 200 people. And i'm trying to get the place.  
About the date, i would prefer the 2nd day afternoon of the conference, i already have a proposal host a NodeJS w/ drone on the 1st day. So 2nd will be a perfect time. 

> How do we promote/handle registration?

If C+L will be part of the JSConf.cn program,  we can use the ticket platform as we use it for JSConf.cn now. And we will send an email for all the attendees who already bought the ticket. And let the other choose if he want have a C+L ticket when he bought the JSConf.cn ticket. At this time, people who attend the C+L won't miss the conference he still be able see the videos afterwards. And we only has the limit slots there, that's why i don't think it will distract people from the conference.

> Travel/Mentors

We definitely need more budget for this section and need more sponsors to sponsor us as well. And thanks for the help from Foundation, and the help from the community . Let's try to make it happen.

**Comment by bengl** [comment]
I've mentored at almost every C+L and I'd like to continue that trend, if it's helpful/possible/reasonable (and if there's budget for it).

**Comment by TimothyGu** [comment]
@xeodou As a Node.js collaborator attending JSConf.cn, should I purchase a ticket from bagevent.com through the usual route as well?

**Comment by DavidCai1111** [comment]
> As a Node.js collaborator attending JSConf.cn, should I purchase a ticket from bagevent.com through the usual route as well?

@xeodou +1

**Comment by JacksonTian** [comment]
Hi @Trott , Count me in too.

**Comment by joyeecheung** [comment]
@xeodou If we use the ticket platform that JSConf China uses, will people who don't attend JSConf China be able to register? Like opening a special scheme for C+L only?

**Comment by Trott** [comment]
> I've mentored at almost every C+L and I'd like to continue that trend, if it's helpful/possible/reasonable (and if there's budget for it).

@bengl I _think_ budget would have to be requested from the Node.js TSC to come out of their travel budget, but I'm not 100% sure about that. @hackygolucky or @mikeal would probably know.

**Comment by pmq20** [comment]
@Trott Thanks for organizing the event, please count me in as a mentor. I am not quite sure what I need to prepare. Do I need to prepare a presentation or just need to be there on time to answer questions?

**Comment by Trott** [comment]
> Do I need to prepare a presentation or just need to be there on time to answer questions?

@pmq20 No preparation needed.

If you happen to come across issues in Node.js that might be good for a first-time contributor, making a note of it would be great.

**Comment by xeodou** [comment]
**Updates for venue**

The venue we rent for conference have a large space in the middle building. We can use it for free which has 50 ~ 80 capacity. Pic see here 
![image](https://cloud.githubusercontent.com/assets/914595/25834590/dd566bfc-342d-11e7-9274-44b83a49b06f.png)

So we will save a lots of money for the C+L event, if the event is really hot we can consider add another one  in the morning. Apparently we don't have the accommodation/travel budget for the mentors. But i think at least we can offer the free tickets for whom mentor for the C+L event.

@TimothyGu  @DavidCai1993 @joyeecheung 

**About the ticket**

I'm not sure we set the price for C+L free for all conference attends (i prefer free personally, need check will @Trott ). But it will be part of the conference program i guess. People who attend the conference have the opportunity to purchase the ticket for C+L and we will send the email for all people who already purchase the ticket already.  And as i mention above we will think to give free tickets for all mentors (big discount without doubt) , will update this under the issue.  


By the way any question or any issues you can ask me here, i will try answer all the questions here.

**Comment by joyeecheung** [comment]
Also remember that there could be a very low chance that GitHub might get blocked during the C+L (I mean, who knows, The Wall has its own way of deciding when to do stuff like this ¯\\_(ツ)_/¯). If something like this happens, I can provide a proxy for people who don't know how to get pass the wall as long as there aren't too many clients, because I am not sure how the wall detect suspicious servers..

(I hope the wall won't have its eye on me because of this post lol, we have good intentions!)

**Comment by addaleax** [comment]
> I'm not sure we set the price for C+L free for all conference attends (i prefer free personally, need check will @Trott ). But it will be part of the conference program i guess.

@xeodou Note that the Foundation has a small budget for this event – if you have any questions about that, @hackygolucky is the one to talk to. :)

**Comment by gibfahn** [comment]
I'd like to help out with this if possible. I'll need to work out the logistics for travel/budget etc.

I speak *some* Chinese...

**Comment by xeodou** [comment]
That's cool. Thanks @addaleax  I will talk to  @hackygolucky directly.

@joyeecheung  I don't think that could be an issue for us. I guess most of the people have the way to access the website that are not existing in China if we provider a proper internet connection. But that's for the backup plan. ;)

**Comment by XadillaX** [comment]
I think I can have a try then.

**Comment by addaleax** [comment]
@xeodou you might be the best person to ask, do you know for sure whether we need a visa to be there or not?

**Comment by joyeecheung** [comment]
addaleax  FWIW, there might be exceptions but the visa thing is usually mutual, so I am guessing if a Chinese citizen like me needs a visa to enter Schengen Area and the U.S., citizens from those places would need a visa to enter China as well? Of course @xeodou should be more familiar with this stuff than I am :)

**Comment by gibfahn** [comment]
I think a [Tourist (L) visa](https://www.travelchinaguide.com/embassy/visa/tourist.htm) should be enough, costs about £85 in London. You need to give hotel and flight confirmations as part of the application. I don't _think_ you'd need a business visa...

**Comment by Trott** [comment]
I am most definitely not an expert on such things, but the same site that @gibfahn linked to and other sources seem to indicate that there's no visa requirement from a number of countries (including Germany and the United States) if your stay is less than 144 hours and if you do not leave Shanghai. https://www.travelchinaguide.com/embassy/visa/free-transit-144hour.htm

**Comment by XadillaX** [comment]
Hey @Trott, may I be a mentor? though I'm not in core.

**Comment by joyeecheung** [comment]
@Trott I think that one is for layovers...? Although that works too if you do travel to a third country.

> Passengers should hold an onward ticket with a confirmed seat and date as well as a valid visa to a third country or region. Hong Kong, Macau and Taiwan count as third regions in term of immigration affairs. For example, the route UK-Guangzhou-UK is not eligible because the passenger does not fly to a third country or region, while the routes UK-Shanghai-Hong Kong, Japan-Nanjing-US, Canada-Guangzhou-Seoul-UK, and Russia-Seoul-Shenzhen-Macau are fine.

**Comment by Trott** [comment]
> Hey @Trott, may I be a mentor? though I'm not in core.

@XadillaX It would probably be a good idea to get a commit into core before the event so that you can help people with things like commit message requirements or how to run the linter without having to run all the tests first. One commit is enough, in my opinion. If you need a quick/simple task so that you can go through the process, check out http://nodetodo.org/getting-started/.

/cc @addaleax

**Comment by Trott** [comment]
> @Trott I think that one is for layovers...? Although that works too if you do travel to a third country.

@joyeecheung Argh! I guess I better get to work on getting a visa then...

**Comment by xeodou** [comment]
> @xeodou you might be the best person to ask, do you know for sure whether we need a visa to be there or not?

for @addaleax  @gibfahn  and the others might interesting about the visa issues

In China we have a new policy citizen from 51 counties can get a 144 hours (**which is 7 days**) visa, for several regions in China, for example if you go to Shanghai ,you will be able stay at Shanghai, Jiangsu, Zhejiang (It's already a big place in China) for 7 days without any problems. 

> 2.Q: Which countries are covered in the policy? 

> A: Currently, there are 51 countries and they are Albania, Argentina, Austria, Australia, Belgium, Bosnia and Herzegovina, Brazil, Brunei, Bulgaria, Canada, Chile, Croatia, Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Iceland, Ireland, Italy, Japan, Latvia, Lithuania, Luxemburg, Macedonia, Malta, Mexico, Montenegro, Netherlands, New Zealand, Poland, Portugal, Qatar, Romania, Russia, Serbia, Singapore, Slovakia, Slovenia, South Korea, Spain, Sweden, Switzerland, United Arab Emirates, Ukraine, United Kingdom, United States of America. 

see more at the immigration website.
http://sh-immigration.gov.cn/listPageEn.aspx?lx=40&id=4414

We actually do this last year, our speaker never get any issues when they pass the custom in Nanjing.

**Comment by xeodou** [comment]
You can buy a flights from you country to Shanghai and make a connection at Japan, Hong Kong ect when you back to your country.

**Comment by xeodou** [comment]
By the way @Trott and the other folks,   if you need a invitation letter from me , i'm very pleasure to do this. We give the letter to help people apply visa to China without any issues.

**Comment by yorkie** [comment]
Sorry for missing this message @Trott, count me in, that's my pleasure :)

**Comment by makara** [comment]
Hi @Trott,

I'm one of the organizers. I didn't know you were discussing here; let me answer your questions with some more details:

> Will Code + Learn be on one of those days? The day before? The day after?
> Will it be part of the JSConf.cn program? Or separate?
> Will we be able to have it take place in the same location? If not, where might be available?
> How many will the space accommodate?

As @xeodou mentioned we'll be able to host it during the conference, so it will be one of the 2 days, and regarding the program there are a few possibilities:

- As @xeodou said we have a separate place that can hold around 50 people. Time slots can be:
    - 2 to 3 hours in the morning
    - 3 to 4 hours in the afternoon
- There's a special case that on Saturday, after dinner, we'll be able to use the main hall until 10pm, and we can expect a few hundred people, but that wouldn't be a typical workshop.

You are free to pick a slot - we'll do our best to collaborate; please let us know.

> How do we promote/handle registration?

We are still discussing the details for registration but we'll handle this. As @xeodou emphasized we hope it'll be free but let us know if it cannot be fully covered by your budget. We'll also promote it and we need a few details from you guys:

- What is the topic/content?
- What is the process/structure? Do you have a guideline/agenda?
- Can we have a short bio of Code + Learn or the organization(s) behind?

Thanks,
Makara

**Comment by Trott** [comment]
> As @xeodou said we have a separate place that can hold around 50 people. Time slots can be:
> * 2 to 3 hours in the morning
> * 3 to 4 hours in the afternoon

I think 3 hours is probably a minimum. 4 hours is better.

> There's a special case that on Saturday, after dinner, we'll be able to use the main hall until 10pm, and we can expect a few hundred people, but that wouldn't be a typical workshop.

I think about 5 attendees per mentor is about right, so the 50-person event is probably the better option.

> As @xeodou emphasized we hope it'll be free but let us know if it cannot be fully covered by your budget.

Budget is definitely something I don't handle. @hackygolucky: Can you help with that information?

> What is the topic/content?

Code + Learn will help you get started with Node.js core contributions. Experienced contributors help guide you through your first commit to Node.js core. They also are available to provide impromptu guided tours through specific areas of Node.js core source code.

> What is the process/structure? Do you have a guideline/agenda?

We usually spend about 10 minutes at the beginning describing the process and providing one or more URLs that will give step-by-step instructions. After that, we mostly walk around the room helping people who run into problems. Once someone has Node.js compiling and tests running successfully, we assign them a first task. Once they've done the (usually simple) first task, we help them through the contribution process. @addaleax: Anything to add? Am I leaving anything out?

> Can we have a short bio of Code + Learn or the organization(s) behind?

https://nodejs.org/en/get-involved/code-and-learn/ 
Organization behind it is the Node.js Foundation
Primary folks organizing/running these things are Anna Henningsen (@addaleax), Tracy Hinds (@hackygolucky) and me

@addaleax @hackygolucky Any additional thoughts?

@bengl has been to all recent Code + Learn events and also might have additional thoughts.

**Comment by joyeecheung** [comment]
@makara Also there is [a post on the Node.js foundation blog](https://medium.com/the-node-js-collection/code-learn-learn-how-to-contribute-to-node-js-core-8a2dbdf9be45) that could probably give you more information on this event (there is even a video!)

**Comment by makara** [comment]
Thanks guys; that looks great.

- Regarding the budget, I thought you know because @xeodou seems already have an idea; We'll check with him.
- It sounds an afternoon is the best option. We'll move forward assuming this.
- Let me know if you need any help, like the hotel address or invitation etc. It'd be also helpful if you could collect all the mentor names in a list and put some notes like who needs what.

**Comment by Trott** [comment]
> Regarding the budget, I thought you know because @xeodou seems already have an idea; We'll check with him.

According to @hackygolucky, she's been coordinating budget stuff with the JSConf.cn organizers (she didn't tell me names, though) so, yes, hopefully that's all being handled between the organizers and the Node.js Foundation.

> It sounds an afternoon is the best option. We'll move forward assuming this.

🎉 

> Let me know if you need any help, like the hotel address or invitation etc. It'd be also helpful if you could collect all the mentor names in a list and put some notes like who needs what.

The hotel address would be great. (If you want to move to email, I'm rtrott@gmail.com.)

I believe most of the mentors reside in China. (@joyeecheung @DavidCai1993 @JacksonTian @pmq20  @XadillaX  @yorkie) <- If your name is in that list and you don't live in China, say something!

@TimothyGu doesn't live permanently in China, but he will already be in Shanghai for other reasons, so I don't think he'll need much in the way of help.

@addaleax will be coming from Germany. @bengl and I will be coming from the United States. An invitation letter from @xeodou or someone else organizing will no doubt help a lot with getting the necessary visa. I believe @hackygolucky has already asked for that, but if not, let me know! (Also, she may not have included @bengl/Bryan English in her list. I'm sure she would have included Anna and me, though.)

**Comment by cocoyu** [comment]
Hi all, I'm also the organizer of JS Conf China.

1. We are putting the C+L workshop on our website early next week. Please provide the following info this week.
- [ ] a brief introduction of the workshop in English (and Chinese if possible)
- [ ] profile photo and short bio of the workshop organizers/ mentors

2. Please confirm the mentor list is correct, we'll send the conference ticket code to everyone's email address.
- Anna Henningsen @addaleax anna@addaleax.net
- Rich Trott @trott rtrott@gmail.com
- Joyee Cheung (Qiuyi Zhang) @joyeecheung joyeec9h3@gmail.com
- David Cai @DavidCai1993 davidcai1993@yahoo.com
- Timothy Gu @TimothyGu timothygu99@gmail.com
- Bryan English @bengl bryan@bryanenglish.com
- Jackson Tian @JacksonTian shyvo1987@gmail.com
- Minqi Pan @pmq20 pmq2001@gmail.com
- Flandre Scarlet @XadillaX admin@xcoder.in i@2333.moe 
- Yorkie Liu @yorkie yorkiefixer@gmail.com

cc// @Trott

**Comment by TimothyGu** [comment]
FWIW my Chinese name is Tiancheng Gu (顾天骋).

**Comment by XadillaX** [comment]
@cocoyu I think

+ Khaidi Chu @XadillaX i@2333.moe

would be fine to me. My Chinese name is 朱凯迪 and nickname is 死月.

**Comment by joyeecheung** [comment]
@cocoyu My Chinese name is 张秋怡. BTW @JacksonTian is one of the announced speakers (朴灵).

**Comment by Trott** [comment]
Very brief introduction of Code + Learn:

> Code + Learn will enable you to get started (or go further) with Node.js core contributions. Experienced contributors help guide you through your first (or second or third or fourth) commit to Node.js core. They also are available to provide impromptu guided tours through specific areas of Node.js core source code.

(@addaleax and @hackygolucky: Feel free to rewrite or amend the above in any way you wish.)

EDIT: Here's the page with description from the last Code + Learn if it helps: http://events.linuxfoundation.org/events/archive/2016/node-interactive/extend-the-experience/codeandlearn

**Comment by Trott** [comment]
> profile photo and short bio of the workshop organizers/ mentors

Because there are so many mentors, perhaps we can use the Node.js Foundation logo as a photo and provide a list of names as the bio text? (@hackygolucky: Do you know if this would violate any rules concerning the use of the logo?)

**Comment by Trott** [comment]
Maybe something like this? Order of mentors is unimportant, I think, so feel free to order however you think is best.

<img width="172" alt="" src="https://user-images.githubusercontent.com/718899/26949343-766c2d1c-4c4e-11e7-8cea-5bbda878ca00.png">
Code + Learn mentors will include the following contributors to Node.js core:

- Anna Henningsen
- Rich Trott
- 张秋怡
- David Cai
- Timothy Gu
- Bryan English
- 朴灵
- Minqi Pan
- Khaidi Chu
- Yorkie Liu

**Comment by pmq20** [comment]
@cocoyu Thanks. My email is correct, with Chinese character name being 潘旻琦 in case of need.

**Comment by XadillaX** [comment]
@cocoyu Do we still need to provide some brief introduce now?

**Comment by cocoyu** [comment]
I think we go it already, thanks!

**Comment by bengl** [comment]
Just to be clear: I have a flight, hotel and a visa, so I'm 100% in. :) (i.e. you can remove the question mark from my handle)

**Comment by TimothyGu** [comment]
@cocoyu I'm one of the mentors but I don't think I've yet received a conference ticket code (as you mentioned you would send in https://github.com/nodejs/code-and-learn/issues/68#issuecomment-307010485). Sorry for rushing you but just wanted to make sure I'm not the only one with this condition :)

**Comment by cocoyu** [comment]
My colleague will send out the tickets this week, cheers!

**Comment by xeodou** [comment]
Hey @Trott  Do we already prepare list of small issues , so every team can work on during the workshop ?

**Comment by Trott** [comment]
@xeodou Yes, I have issues prepared.

**Comment by Trott** [comment]
Will there be some kind of internet connection for Code + Learn attendees? (An email today indicates that there would not be Wi-Fi at the venue.)

**Comment by cocoyu** [comment]
Hi, we do have wi-fi for all the speakers, workshops and staff.

**Comment by xeodou** [comment]
@Trott We have internet, but i can't promise the speed. So if we required pull a town of packages, we can ask them prepare them before the workshop.

**Comment by TimothyGu** [comment]
Just a N.B. for everyone coming over from abroad: Generally for package downloading, domestic mirrors are preferred due to the uhm special Internet conditions in China.

Taobao provides mirrors in China for Node.js and npm: https://npm.taobao.org/

Tsinghua University provides mirrors for a bunch of Linux distros and package managers, include Debian, Ubuntu, Homebrew: https://mirror.tuna.tsinghua.edu.cn/

**Comment by gibfahn** [comment]
@TimothyGu is the Taobao mirror a full one (i.e. it contains everything)? How long does it take things to get into it from npmjs.org?

Really useful info btw, do you have any articles/resources with more information? Maybe something we could document in nodejs.org

**Comment by XadillaX** [comment]
@gibfahn yeah it's a full mirror. it sync every 15 minutes (or some interval other? I'm not sure)

If you download a package that hasn't synced yet, mirror will sync that package immidiately.

**Comment by TimothyGu** [comment]
@gibfahn Yep it is. The website says "同步频率目前为10分钟" so 10 minutes, but you can actually [manually request a resync](https://npm.taobao.org/sync/pug) too. Can't say I've seen any articles relating to mirrors in China, and I mean this information is pretty specific to China so not sure if nodejs.org is the best place for that. I've created https://github.com/TimothyGu/survive-in-china though, will add some stuff when I get the chance to.

**Comment by gibfahn** [comment]
We have a bunch of guides in [docs/guides](https://nodejs.org/en/docs/guides/) talking about how to do things in Node. As China presents a unique challenge to Noders, I think a guide to using Node in China might be very helpful. I notice that none of the existing guides have been translated into Chinese yet (https://nodejs.org/zh-cn/docs/).

Just judging by the issue tracker, there's clearly a large number of Chinese node users getting involved, which is great to see. I think we could be a lot more organised in how we help them though (probably applies to other countries too, I'm just more familiar with China).

Obviously if nodejs.org is blocked then there's not much point 😉

**Comment by joyeecheung** [comment]
Right now cnpmjs.org can sync with npmjs.org in near-realtime because it is subscribed to the npm change stream. It uses a server in Singapore to relay the traffic between China and U.S.. @fengmk2 knows more about the details.

**Comment by fengmk2** [comment]
According the sync log https://r.cnpmjs.org/alcedo-ui/sync/log/3749013 , sync delay between cnpmjs.org and npmjs.org is below 10s. 

I think it's the fastest npm registry mirror of the world.

> [2017-07-13 16:20:41]     [alcedo-ui:0] syncing, delay: 2491 ms, version: 1.0.68, dist: {"integrity":"sha512-FKj9EXpxrO3I3EABEF0um48urX9ay9YptTeGSs1nQ/c8FSZXkbGPCFQbO7Zfc5UfogbVWNhWY/PXsWxgtkXreQ==","shasum":"4509a769d8a5102cf2a9857afa5ada9a9677f29a","tarball":"https://registry.npmjs.org/alcedo-ui/-/alcedo-ui-1.0.68.tgz"}, no deps: false, publish on cnpm: false, dependencies: 0, devDependencies: 0, syncDevDependencies: false

**Comment by joyeecheung** [comment]
BTW the whole cnpm solution is open sourced: https://github.com/cnpm/ For example, see https://github.com/cnpm/cnpmjs.org/tree/master/sync on how the synchronization works

**Comment by joyeecheung** [comment]
I believe completing these steps before the workshop will save most of the bandwith for attendees (gonna use Chinese here):

1. 安装编译器与构建工具
    * Linux
        * gcc 和 g++ 4.9.4 或更新的版本（或 clang 和 clang++ 3.4.2 或更新的版本)
        * GNU Make 3.81 或更新的版本
        * Python 2.6 或 2.7
    * Mac:
        * [Xcode](https://developer.apple.com/xcode/) 和最新的 Xcode Command Line Tools (`xcode-select --install`)
    * Windows
        * [Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools)，或 [Visual Studio 2015 Update 3 或更新的版本](https://www.visualstudio.com/downloads/)，或 [Visual Studio 2017](https://www.visualstudio.com/downloads/)
        * Python 2.6 或 2.7
2. Clone [nodejs/node repo](https://github.com/nodejs/node), 如果不需要 git 历史可以用 `git clone --depth=1` 加快下载

(详细参见 [BUILDING.md](https://github.com/nodejs/node/blob/master/BUILDING.md))

@xeodou @cocoyu Can you notify the attendees about this? The instructions can be more specific, but I believe most attendees should already know how to do these (at least cloning the repo beforehand would help).

**Comment by xeodou** [comment]
Cool. Thanks @joyeecheung  will send the email to the workshop attendees tonight.

**Comment by bengl** [comment]
@xeodou Will power strips be available? Compiling node can often drain one's battery 😄

**Comment by Trott** [comment]
@nodejs/collaborators If anyone remote wants to help out, it would be great if someone or someones could watch the issue tracker, label issues that come in as `code-and-learn`, provide code reviews in near-realtime, and (when appropriate) kick off CI jobs. Let me know if you plan on doing that, and let's keep in touch in IRC in case anything comes up!

If anyone at JSConf.cn wants to find me before the workshop, I'm wearing a black t-shirt that says "i <3 my internet friends" on it.

**Comment by Trott** [comment]
For the remote help I asked for above:

The workshop starts at 14:10 Shanghai time (CST) which is:


Location | Local Time | Time Zone | UTC Offset
-- | -- | -- | --
New York (USA - New York) | Monday, July 17, 2017 at 2:10:00 am | EDT | UTC-4 hours
San Francisco (USA - California) | Sunday, July 16, 2017 at 11:10:00 pm | PDT | UTC-7 hours
Berlin (Germany - Berlin) | Monday, July 17, 2017 at 8:10:00 am | CEST | UTC+2 hours
Moscow (Russia - Moscow) | Monday, July 17, 2017 at 9:10:00 am | MSK | UTC+3 hours
Chennai (India - Tamil Nadu) | Monday, July 17, 2017 at 11:40:00 am | IST | UTC+5:30 hours
Sydney (Australia - New South Wales) | Monday, July 17, 2017 at 4:10:00 pm | AEST | UTC+10 hours
Tokyo (Japan) | Monday, July 17, 2017 at 3:10:00 pm | JST | UTC+9 hours
Shanghai (China - Shanghai Municipality) | Monday, July 17, 2017 at 2:10:00 pm | CST | UTC+8 hours
Corresponding UTC (GMT) | Monday, July 17, 2017 at 06:10:00 |   |

**Comment by gireeshpunathil** [comment]
@Trott - I will keep a watch. Will there be any special `tags` in the issue that indicate they emanate from the conference? or it is un-necessary?

**Comment by Trott** [comment]
@gireeshpunathil Since the people opening the PRs don't have the ability to add labels, they won't have any special tags/labels. We'll probably ask them to mention "Code + Learn" in the PR, though.

**Comment by Trott** [comment]
@gireeshpunathil Also, THANKS!!!!

**Comment by Trott** [comment]
(Also, I listed the start time above, but PRs probably won't start coming in for at least a half hour, and probably more like an hour, after starttime.)

**Comment by bengl** [comment]
super helpful https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#resolving-common-issues

**Comment by TimothyGu** [comment]
I guess we can close this now. It was a blast seeing everyone there!

**Comment by Trott** [comment]
Thanks, everyone! It was an amazing experience for me. I hope it was fun and useful for everyone else!

**Comment by jasnell** [comment]
Sounds like it was a great event! Thanks all!
