### ISSUE TITLE
Mentors for Code-and-Learn @ NodeConf EU (Nov 6)

### ISSUE THREAD

**Issue by jasnell** [nodejs/code-and-learn#69]
@nodejs/codeandlearn (and in particular @Trott and @addaleax) ... 

@mcollina and I are planning to run a Code-and-Learn event as part of the NodeConf EU conference in Ireland on November 6th. We're looking for core contributors to help mentor. We're looking to have about 200 people attending the conference so we could end up with a large number attending the Code-and-Learn.

**Comment by addaleax** [comment]
Count me in – I think @hackygolucky has been planning on having both @Trott and @addaleax there for exactly that anyway.

**Comment by Trott** [comment]
> I think @hackygolucky has been planning on having both @Trott and @addaleax there for exactly that anyway.

Yes, what @addaleax wrote: I've been 100% planning on being there.

**Comment by refack** [comment]
Nov 6 is my bday 😊  ... I'd love to come, pending visa issue resolved.

**Comment by Trott** [comment]
Ping @nodejs/collaborators: Who is coming to NodeConf EU and willing to be a mentor at the Code + Learn there? Will be smaller than the one at Node Interactive, but it would still be great if we could have a good 20 mentors ideally.

- [x] @jasnell
- [x] @mcollina 
- [x] @addaleax 
- [x] @Trott
- [x] @lucamaraschi 
- [ ] You?
- [ ] You?

**Comment by jasnell** [comment]
Ping @nodejs/collaborators ... :-)

**Comment by benjamingr** [comment]
Sounds awesome, I would have loved to attend - I'll do my best to make the next one. 

Thanks for doing this @Trott @jasnell @addaleax !

**Comment by mcollina** [comment]
I can volunteer @lucamaraschi.

**Comment by joyeecheung** [comment]
Hi everyone, I would not be able to be there (sadly), but I have a few ideas on the tasks (https://github.com/nodejs/node/issues/16616#issuecomment-340526461), can you consider trying it out in this code-and-learn event? :

1. Ask participants to add a description to the test (the `This tests that....` comment) that they are working on, if there isn't one and they feel confident enough to do that.
2. Add a `// Subsystems:` comment to the test file about the subsystems that it is testing.

Sorry if this is the wrong place to post, but this event is the most near one and I want to know how the mentors feel about this.

**Comment by Trott** [comment]
@joyeecheung Comment explaining the test seems straightforward and we can do that.

The subsystem metadata is something that might require some discussion with more collaborators. Will comment over in that other issue.
