### ISSUE TITLE
Write a guide on environment setup, troubleshooting, and preparations (e.g. downloads)

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/code-and-learn#71]
We should collect these information in a central place (maybe a document in this repo) and send it out to participants before the event.

Also a FAQ covering things like

* I am seeing some unrelated test failures, is that OK?
* What does it mean to replace fixturesDir with fixtures?
* Which branch should I target?
* Reviewers asked me to rebase, what does it mean?
* etc.

would be very useful.

**Comment by joyeecheung** [comment]
FTR I am writing one (and trying to do a screencast on the build & test & git stuff), but I've got my hands pretty full right now so probably won't finish them anytime soon. Anyone willing to do it can take it now.

**Comment by Trott** [comment]
Ping @nodejs/collaborators: If anyone wants to write something like this up and put it somewhere linkable that would be great. Speaking just for me, a pull request adding a page like this to https://github.com/Trott/nodetodo would be super-duper welcome.

**Comment by gibfahn** [comment]
Related: https://github.com/Trott/nodetodo/issues/4

**Comment by bzoz** [comment]
I've created a Boxstarter script for Windows boxes. PR to include it in Node: https://github.com/nodejs/node/pull/17046
