### ISSUE TITLE
Code And Learn on recruit technologies inc

### ISSUE THREAD

**Issue by yosuke-furukawa** [nodejs/code-and-learn#78]
I have a lesson for OSS contribution in my company (Recruit Technologies).

We don't have a practice to contribute OSS but we would like to take some practices on Code And Learn. 
I have some contribution points to refactor test dir.
I think I would be better to notify some contributors get some PRs.

**Comment by benjamingr** [comment]
When is this? I wouldn't mind helping with reviews for PRs.

**Comment by yosuke-furukawa** [comment]
> When is this? I wouldn't mind helping with reviews for PRs.

this is today (sorry). 

I could review and it is ok if you would not help our PRs.

**Comment by yosuke-furukawa** [comment]
Thank you for collaborators review. it is finished. we have created 4 new node.js committer by OSS newbies.
