### ISSUE TITLE
Next events?

### ISSUE THREAD

**Issue by fhinkel** [nodejs/code-and-learn#80]
We currently don't have anything scheduled. What are the plans for the next Code and Learns? Is there one planned in conjunction with [JSConfEU](https://2018.jsconf.eu/)? Anything happening in the bay area soon? 

I'd like to host one in conjunction with ngAtlanta in 2019. Anybody interested in helping me? 

cc @Trott @addaleax

**Comment by Trott** [comment]
As far as official Foundation-sponsored ones go: I don't know if the budget got approved and/or what was in it (even though @hackygolucky ran all that stuff by me and @addaleax--my memory is foggy right now--I might try to search through old email). With the Foundation's Education Coordinator position still vacant, this needs an energetic champion to make stuff happen (or maybe the position will be filled imminently?). Last year was a banner year for Code + Learn (3 continents! 4 countries! And that's just the official Foundation-sponsored ones! There were additional ones in Japan and Taiwan, I think!). Would be nice to not lose all that momentum this year!

/cc @mrhinkle

**Comment by benjamingr** [comment]
I'd love to organize another (smallish) event in Israel if anyone is ever around. We have monthly open source events and I'd love to see Node take a more predominant role

**Comment by mcollina** [comment]
I'm pretty confident we can run another one within NodeConfEu, which will be at the beginning of November (same as last year).

**Comment by benjamingr** [comment]
What about the collab summit in May?

**Comment by amitbend** [comment]
Waiting for an event in Israel!

**Comment by benjamingr** [comment]
@amitbend we've had one since and we're having the next one (small) in June 19th, you are [welcome to attend](https://www.meetup.com/JavaScript-Israel/events/250979710/).

**Comment by trivikr** [comment]
I'd conducted an informal one at [WebDevCon](http://webdevcon.com/) in April 2018 at Seattle (Amazon's internal Front-end conference).
We're conducting another one at WebDevCon EU in July 2018, but that's also internal to Amazon.
The aim is to conduct an external one (open to all) in Seattle during WebDevCon in October 2018.

**Comment by Trott** [comment]
For anyone wanting to contribute to Node.js core without waiting for a Code + Learn event they can attend: https://www.nodetodo.org/

**Comment by amitbend** [comment]
@benjamingr @Trott  Thanks!

**Comment by fhinkel** [comment]
Looks like we'll have two events this fall. One in Europe and one in North America: 

https://github.com/nodejs/code-and-learn/issues/81
https://github.com/nodejs/code-and-learn/issues/84

And potentially one in China: 
https://github.com/nodejs/code-and-learn/issues/85
