### ISSUE TITLE
Scope of Code + Learn for JS Interactive 2018

### ISSUE THREAD

**Issue by Trott** [nodejs/code-and-learn#82]
After talking a bunch with @rachelnicole (whose initial idea most of this is, I believe), @bnb, and @addaleax: 

Don't know if it would be part of Code + Learn or an event that happened at the same time but was separate, but it seems a slam-dunk to have a help-out-with-the-website session/sprint and/or a help-out-with-translations session/sprint as long as there are knowledgable folks from those areas willing to do the work to make it happen. 

Thoughts? If this seems like a good idea, how do we move it forward?

@nodejs/website @nodejs/i18n @MylesBorins @trivikr

**Comment by trivikr** [comment]
I didn't get the suggestions correctly.
I'm 👍for mentoring in Code+Learn during JSInteractive 2018

**Comment by gireeshpunathil** [comment]
I wish if we could leverage this code&learn aiming to reduce our backlog of issues in nodejs/node repo, 

While it may not be easy to guide first timers to address complex problems,
 - we do have ample time between now and then
 - few of those may have a fast path to resolutions
 - there are good amount of flaky tests that can be helped with
 - there are minor to medium scale feature requests which attendees can pick up and do over a period of time

My bottom line is it may be tough, but investing any effort is meanngiful. I am willing to help.

**Comment by zeke** [comment]
Is this strictly an in-person thing?

**Comment by ZibbyKeaton** [comment]
Likely something to discuss further on, but once we have the schedule and all the materials locked into this, I'm happy to draft up copy around C+L for the JS Interactive website. We could also do a blog post about the event as well to help drive attendance and awareness.

**Comment by Trott** [comment]
> Is this strictly an in-person thing?

@zeke Yes, or at least it has been in the past. Ignoring the proposed expanded scope here for a moment, the remote/async version (but not Foundation-sanctioned) would be https://www.nodetodo.org/.

**Comment by mikeal** [comment]
What does "Foundation-sanctioned" mean in this context?

The tool was built by project committers for the project. Those contributors make up the technical side of the foundation. Is there some sort of blessing or support you'd like to see from the foundation that you haven't received?

Ownership is sort of a weird construct here because contributors to the project always retain ownership of their contributions, so I'm wondering if 1) you *want* to keep this separate from the project/foundation for community building or other reasons and 2) you'd like to see some kind of official support you haven't received.

**Comment by Trott** [comment]
> What does "Foundation-sanctioned" mean in this context?

@mikeal That's a really good question. Here's why I said that.

Sometimes James or Myles (or you!) will say or tweet something, and people will attribute the sentiment to Node.js as a whole. I've done a fair amount of explaining that Node.js is not monolithic and no one person speaks for the project. It's an uphill battle.

At this point, emphasizing that NodeTodo-is-not-a-Foundation-thing is a variation on making that point. Code + Learn in Vancouver really does reflect the Foundation, at least to some extent. The Foundation supplies resources for it and so on. NodeTodo is just a website I put up, an email address I respond to, and a Twitter handle I infrequently tweet from.

When I first started doing it, the separation from the official Node.js project was intentional. But the concerns and attitudes that led me to approach things that way are in the past, or at least not on my mind as much these days.

**Comment by Trott** [comment]
I think at this late date, we've missed the boat on this. If anyone wants to dive in and make this happen, please comment or re-open. Otherwise: Closing.
