### ISSUE TITLE
Code + Learn Copy for the JS Interactive Website

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/code-and-learn#83]
We would like to post information on the Code + Learn on the JS Interactive website. Below is my suggested copy. Folks will have the opportunity to register when they check out (similar to what we've done in years past).

Please let me know if this copy looks good as soon as you can. I would like to get this posted the website on Wednesday (August 1) as we have a blog to promote all our add-ons at the conference. If we need to make some small edits, later on, we should be able to do so.

_**Code & Learn**
Date: October 12, 2018
Time: 9:00-12:00 pm
Location: Room 121/122
Cost: Complimentary to JS Interactive attendees; Pre-registration required.
Code & Learn events allow you to get started (or go further) with Node.js core contributions. Experienced contributors help guide you through your first, second or third commit to Node.js core. 
If you are looking to become a part of the Node.js community or curious to learn how to contribute to Node.js core, this is a must-attend event. Please be sure to register for the event in advance as space is limited. This event is free to attend and is happening after the official JS Interactive conference.
**EVENT DETAILS** 
Date: October 12, 2018
Time: 9:00-12:00 pm
Location: Room 121/122
Registration Cost: Complimentary; Pre-registration required.
**How to Register:**
Pre-registration for this session is required. When you register, you will be given the option to register for this during check out._ 

cc: @Trott @addaleax @rachelnicole

**Comment by mcollina** [comment]
+1.

**Comment by mcollina** [comment]
Are mentors supposed to register for this? I didn't last year.

**Comment by ZibbyKeaton** [comment]
Not sure... Let me check in with our events folks to see what they would like to do here (the person who would know all this is on PTO today). I believe we might want to have a registration process, so we know how many folks we can accommodate. Will get back to you on this asap :)

**Comment by Trott** [comment]
Looks good to me other than just one issue: Seems to be different descriptions of the cost: "Complimentary to JS Interactive attendees" vs. "free to attend".  The first one implies there's a cost for people who aren't Interactive attendees, and the second one seems to imply anyone can attend at no cost. FWIW, my preference would be: Free to attend for anyone, but registration is required. I'd be OK with opening it to JS Interactive attendees first and the wider public after. 

Related but not requiring any content changes: Obviously, we won't be able to handle more people than can fit in the room, but beyond that, my experience has been that a 5-attendees-to-1-mentor ratio is a good one to keep things from getting too stressful during the busier moments.

**Comment by ZibbyKeaton** [comment]
Good catch @Trott it should read "Complimentary to JS Interactive attendees." We can expand this further out, however this event generally books up quickly.

@dshaw had asked in a different thread what the process was for registering mentors for Code + Learn. The JS Interactive team is happy to help organize this if the Code + Learn folks would like us too. We can create a special form, etc. 

If y'all want some help with organizations, let's hop on a call to talk about needs and logistics here. Just email me @ zkeaton@linuxfoundation.org.

**Comment by Trott** [comment]
> what the process was for registering mentors for Code + Learn. 

In the past, we just open an issue and people indicate they'll attend and do it.

> If y'all want some help with organizations, let's hop on a call to talk about needs and logistics here. Just email me @ zkeaton@linuxfoundation.org.

Good idea probably to touch base every few weeks. I'll email you.

**Comment by Trott** [comment]
Seems like this can be closed. Re-open or comment if I'm wrong about that!
