### ISSUE TITLE
Mentors for Code + Learn @ Node+JS Interactive 2018

### ISSUE THREAD

**Issue by Trott** [nodejs/code-and-learn#84]
Code & Learn
Date: October 12, 2018
Time: 9:00-12:00 pm
Vancouver BC CAN

I don't *think* there's another issue identifying mentors for this event, so let's get it going here. (And if one is open somewhere else, link it here, close this, and accept my apology in advance.)

1. Rich Trott (@trott)
1. Anna Henningsen (@addaleax)
1. Matteo Collina (@mcollina)
1. Ali Sheikh (@ofrobots)
1. Michaël Zasso (@targos)
1. Julien Gilli (@misterdjules)
1. Myles Borins (@MylesBorins)
1. Sam Roberts (@sam-github)
1. Tobias Nießen (@tniessen)
1. Trivikram Kamat (@trivikr)
1. Ruben Bridgewater (@BridgeAR)
1. Anatoli Papirovski (@apapirovski)
1. Joyee Cheung (@joyeecheung)
1. Guy Bedford (@guybedford)
1. Ujjwal Sharma (@ryzokuken)
1. Shelley Vohr (@codebytere)
1. Bryan English (@bengl)
1. Lance Ball (@lance)
1. Michael Dawson (@mhdawson)
1. Vladimir de Turckheim (@vdeturckheim)
1. Matheus Marchini (@mmarchini)
1. Benjamin E. Coe (@bcoe)
1. James M Snell (@jasnell)
1. Franziska Hinkelmann (@fhinkel)
1. Gabriel Schulhof (@gabrielschulhof)
1. Hitesh Kanwathirtha (@digitalinfinity)
1. Сковорода Никита Андреевич (@ChALkeR)
1. George Adams (@gdams)
…

Who else? (Feel free to edit this to add yourself to the list above.)

**Comment by Trott** [comment]
@nodejs/collaborators

**Comment by mcollina** [comment]
Count me in.

**Comment by ofrobots** [comment]
I'd be happy to help.

**Comment by targos** [comment]
I'm in

**Comment by misterdjules** [comment]
I'd like to help too!

**Comment by MylesBorins** [comment]
mememe

**Comment by tniessen** [comment]
I'll most likely be there (and have some ideas).

**Comment by trivikr** [comment]
In 👍

**Comment by BridgeAR** [comment]
Count me in.

**Comment by apapirovski** [comment]
I thought there was one already. Either way, I'm in.

**Comment by joyeecheung** [comment]
I'll be there

**Comment by guybedford** [comment]
I'd be glad to join.

**Comment by ryzokuken** [comment]
I'd love to help out.

**Comment by codebytere** [comment]
👋 also down!

**Comment by lance** [comment]
I'll be there!

**Comment by mhdawson** [comment]
I'll be there and happy to help as well.  Added to list as suggested.

**Comment by addaleax** [comment]
@nodejs/collaborators Any more volunteers here? We’d love to get something around 40 – 50 collaborators (or previous contributors) involved as mentors for this. :slightly_smiling_face:

**Comment by vdeturckheim** [comment]
It would be the first time, but I should be there!

**Comment by Trott** [comment]
/ping some members of @nodejs/collaborators that I know plan to be there: @davisjam @ChALkeR @guybedford

**Comment by Trott** [comment]
Related note: @bengl Were you the thumb-drive provider last year? Lessons learned? Things we should do differently? Things we need to make sure we do again because it worked so well? 

We'll definitely email all attendees ahead of time with instructions to install required build tools and implore them to do it at least one day before Code + Learn.

Maybe lots of us can make time to sit at the community booth thing that was just announced to help folks get set up for Code + Learn (install all the build tools, clone the repo), and then advertise that that's a thing that's happening at that booth. (And do it for non-Code + Learn attendees who just want to get started with it too?)

**Comment by mmarchini** [comment]
I'd love to help too!

**Comment by bengl** [comment]
> @bengl Were you the thumb-drive provider last year?

I didn't purchase the thumb-drives. That was done by someone on the foundation side (I can't recall who), and there were 20 of them, IIRC. What I did was take all of them and put a zip file containing a recent clone of the repo on them. 

Unfortunately I have no idea where these thumb-drives are now, and it's possible that I took them at the end and lost them, so I'm happy to replace them if we can't track them down.

> Lessons learned? Things we should do differently? Things we need to make sure we do again because it worked so well?

I distributed the thumb-drives to mentors, but didn't give any to attendees personally. For some reason it seemed that @mcollina asked me for them the most, so maybe Matteo can comment? I think less than 10 of them actually got used. This could be due to communication issues (maybe people didn't know they were available?). It could also be that the network just wasn't that bad so people were able to clone the repo without much issue. I don't know.

One thing that also seemed to work well is folks setting up HTTP git mirrors on their computers and then having that URL on the projector. We should probably try to support that as well.

In any case, distributing some instructions on how to use the thumb-drive or git mirrors would be helpful.

**Comment by Trott** [comment]
> Unfortunately I have no idea where these thumb-drives are now, and it's possible that I took them at the end and lost them, so I'm happy to replace them if we can't track them down.

I think you might have entrusted them to me. I'm pretty sure I stashed them away with all the pins. I have it on my calendar to find all that stuff tonight when I'm home.

**Comment by Trott** [comment]
> I think less than 10 of them actually got used.

Might be also the effectiveness of the Foundation email to attendees instructing them to install devtools and clone the repo the day before arriving.

**Comment by bcoe** [comment]
I'm hoping to be in Vancouver for this 👍

**Comment by addaleax** [comment]
Maybe another very gentle ping in the direction of @nodejs/collaborators ? :)

**Comment by Trott** [comment]
Hi, everyone!  Two things I'd ask you to consider getting in touch with me about:

1. As you may be aware, I come to these things with a stack of paper slips with tasks on them. If you think you have some good Code + Learn tasks that could be handed out in Vancouver, get in touch via email or Twitter DM or IRC messaging or something. (My email is in my GitHub profile.)

2. One thing I'd love to be able to do this year is identify a few mentors who might be up for some more focused mentoring for some slightly more challenging tasks that could be handed out. If you're someone who feels like we give out tasks that aren't as significant as you would like to see, then volunteering for focused mentoring (and maybe even suggesting a few tasks you'd do that for) might be just the thing to make this Code + Learn the best one yet. Get in touch!

**Comment by Trott** [comment]
I'm putting together tasks and there's one (and maybe several) that may require some N-API help. Any @nodejs/n-api volunteers for mentoring?

**Comment by mhdawson** [comment]
I can volunteer for the N-API mentoring, and I think @gabrielschulhof will also be around.

**Comment by NickNaso** [comment]
I will be there and I'm available for the N-API mentoring if necessary.

**Comment by jschlight** [comment]
I am also available for N-API mentoring.

**Comment by Trott** [comment]
(Added @digitalinfinity to list of mentors.)

**Comment by refack** [comment]
> I'm putting together tasks and there's one (and maybe several) that may require some N-API help.

I don't know if people will find it interesting, but IMHO adding comments to tests (or even code) would be very valuable.
Describing tests and subtests.
Referencing non trivial code to its originating PR.
Maybe stuff to help https://github.com/nodejs/node/pull/22405 (make source easy to ref from the docs)

**Comment by ChALkeR** [comment]
@Trott I got my visa and flight tickets last week, so I'm pretty certain that I will be there.

I suppose you could count on me being available for Code+Learn. :smiley: 
I did not participate in Code+Learn previously, but I have some university teaching assitant experience.
I would be glad to be of help.

**Comment by joaocgreis** [comment]
> We'll definitely email all attendees ahead of time with instructions to install required build tools and implore them to do it at least one day before Code + Learn.

I won't be able to be there, but want to leave a friendly reminder that we have https://github.com/nodejs/node/tree/master/tools/bootstrap . This should be the easiest way to tell attendees how to install the tools on any system, and there is even a Boxstarter script that should make it straightforward on Windows. Have a good Code+Learn!

**Comment by BridgeAR** [comment]
Thanks a lot to all mentors! It was a great event!
