### ISSUE TITLE
Mentors for Code + Learn @ NodeConf Colombia 2019

### ISSUE THREAD

**Issue by edsadr** [nodejs/code-and-learn#87]
Code & Learn
Date: June 21st, 2019
Time: 14:00-18:00 COT
Medellin, Colombia

This will be the first NodeConf in Colombia; we will have @addaleax and @jasnell as speakers, @bnb will be speaking too, we can use as much help as @nodejs/collaborators can provide, we have a very active community powered by previous JS conferences and a lot of local meetups, we expect around 300 attendees in the conference an 150 for Code+Learn.

Current mentors attending:

1. @julianduque 
2. @edsadr 
3. @estrada9166
4. @jvelezpo 
5. @addaleax 
6. @jasnell 
7. @bnb 
8. @ryzokuken 
9. @vdeturckheim 
10. @BridgeAR

**Comment by julianduque** [comment]
Hello, we included a **Code & Learn Supporter** tier in our [sponsorship prospectus](https://colombia.nodeconf.com/assets/NodeConfCo_Prospectus.pdf) if any company wants to sponsor more mentors for our Code & Learn, please share and join us in Medellín next year!

<img width="942" alt="screen shot 2018-11-21 at 3 37 16 pm" src="https://user-images.githubusercontent.com/733877/48867192-66814480-eda3-11e8-8a0c-deecfc3e45e4.png">

**Comment by mikeal** [comment]
@julianduque that's a brilliant idea and super generous, thanks! :)

**Comment by julianduque** [comment]
Thanks, @mikeal, the idea was inspired by @fhinkel and this can help us and our attendees have a great experience :)

**Comment by devrchancay** [comment]
I do not understand this well @julianduque, it means that my company sponsors the trip and the hotel and you give me an entry to nodeconf.

What does it mean to be a mentor?

**Comment by julianduque** [comment]
@devrchancay this is for Node.js Collaborators & Contributors that can be mentors of Code & Learn, if you are part of the Node.js project, sure, you are more than welcome :)

**Comment by devrchancay** [comment]
Understood thank you, I'm not a collaborator that's one of my next goals thank you.

PD: I'm about to buy the ticket, I hope to greet you there.

**Comment by julianduque** [comment]
@devrchancay so, please join us at Code & Learn, that's the main idea behind the event, start contributing and become a collaborator!

**Comment by devrchancay** [comment]
@julianduque Can I send a DM on twitter to talk more about that?

**Comment by ryzokuken** [comment]
@julianduque I'd love to volunteer for mentoring the C+L.

**Comment by julianduque** [comment]
@ryzokuken thanks!!! we will take you into account once we have our first sponsored mentor. ;)

**Comment by SuperCamiloTD** [comment]
@julianduque I'd love to volunteer for mentoring the C+L. x2

You can check my main repo: https://github.com/CamiloTD

**Comment by julianduque** [comment]
@SuperCamiloTD Hey! Thanks for your interest and really appreciated! 

Code+Learn mentors are Node.js Contributors/Collaborators that will help others submit their first (or 2nd, or 3rd, or 4th....) commit to the Node.js core project so that is a requirement to be a mentor, but, if you are going to attend the conference you are always welcome to participate :)

And of course, once you get the experience and start contributing to the project you can join us as a mentor for next year! (same for @devrchancay)

More info here: https://nodejs.org/en/get-involved/code-and-learn/

**Comment by vdeturckheim** [comment]
@julianduque @edsadr I should be around and would love to help there!

**Comment by julianduque** [comment]
Event was a success!!! Thank you all for helping <3 <3 <3
