### ISSUE TITLE
Mentors for Code-and-Learn @ Seattle (Dec 18)

### ISSUE THREAD

**Issue by trivikr** [nodejs/code-and-learn#90]
Code & Learn
Date: Tuesday, December 18th, 2018
Time: 18:00-21:00 PST
Venue: Galvanize Seattle ([link](https://www.galvanize.com/seattle/campus))

Galvanize is expecting 14 students (currently enrolled with their Web Development Course) to attend, but they are interested in making this event open to public. They'd organized workshops with upwards of 60 people in the past.

I'm planning to advertise this event during my SeattleJS talk on "How to contribute to Node.js" at SeattleJS December Meetup which on Dec 13th ([details](https://github.com/seattlejs/seattlejs/issues/137))

Before making the event public, I wanted to know if any collaborators are free and can join - preferably if you're from Seattle area.

cc @nodejs/collaborators

**Comment by trivikr** [comment]
cc @nodejs/chakracore as they're likely to be from Seattle area

**Comment by trivikr** [comment]
CCing members of @nodejs/chakracore individually
@agarwal-sandeep @aruneshchandra @boingoing @curtisman @digitalinfinity @EdMaurer @ianwjhalliday @kfarnung @kunalspathak @obastemur @sethgaurav

**Comment by digitalinfinity** [comment]
Aaaah @trivikr this is awesome and I'd have loved to have helped out but I'm out of town during this time 😢 - if you organize this again next year, please let me know and I'll try to help!
Other @nodejs/node-chakracore folks, if you have availability, I encourage y'all to go, it's a great way to help people who are eager to learn about Node. Also cc @michellopez @yodurr since they'll be interested.

**Comment by Trott** [comment]
In the interest of continuous improvement of Code + Learn events, I'd ask that at this and future events, we make sure to encourage participants to:

* Create meaningful PR descriptions and titles.
* Read and comply with the GitHub PR template. 
* Refrain from putting together multiple unrelated changes in different files into a single PR.
* Refrain from doing more than one task handed out at the event. Second tasks should involve finding something more interesting and meaningful (such as improving test coverage) than being asked to change a function to use arrow syntax. There is a list of suggestions at https://www.nodetodo.org/next-steps/. Additions and improvements to that list are more than welcome.

**Comment by targos** [comment]
I would also ask the organizers to avoid giving tasks that are purely style changes and/or that can be done automatically with `eslint --fix`.
I'm thinking especially about the tasks that change regular functions to arrow functions. IMO those changes do not improve the code base, make the git history harder to browse and sometimes remove useful information (For example: https://github.com/nodejs/node/pull/24606 where we lose the names - ). We are also teaching something wrong to the developers: arrow functions are not the only correct way to write callbacks and were not created as a replacement for regular functions.

**Comment by lpinca** [comment]
I totally agree with @targos

**Comment by trivikr** [comment]
Resolving this issue, as the event is postponed because proximity to the holiday season and lack of mentors.

We're planning to organize it either in late-Jan or early-Feb, and I'll create a new issue for it.
