### ISSUE TITLE
JSConf Budapest 2019 would like to hold a Code & Learn Workshop

### ISSUE THREAD

**Issue by necccc** [nodejs/code-and-learn#91]
Hi there,

I attended the Code & Learn workshop on NodeConf EU 2018, and loved it! 
I'm one of the organizers of [JSConf Budapest](https://jsconfbp.com/), and I think many of our attendees would like to learn and start contributing to Node in 2019!

The conference is on Sept 25-27 2019 (3 days with CSSConf Budapest included), 
Wednesday-Friday.

Our workshop day is planned for Tuesday, Sept 24th 2019 - this day would be filled with workshops, free for every ticketholder at the conference. Among many product related, sponsored workshop, I think this would be a great addition!

We would provide free tickets for the mentors to the conference of course! If Node Foundation cannot sponsor us with the workshop costs (mentor travel & hotel), we could help find sponsors!

Thank you for considering!

**Comment by mcollina** [comment]
(I told @necccc to open this issue)

This is a fantastic idea, +1. I think the travel fund should be able to cover the traveling.

**Comment by Trott** [comment]
I know it's a long way off at this point, but do you have an approximation of how many attendees you would expect at the Code + Learn session?

**Comment by necccc** [comment]
At the conference we'll have around 480 ppl, around 20% of them attended some workshop last time we had a workshop day - we hope we can raise that number for 2019, because in our feedbacks 43% said they would attend a free workshop next time.

I would say 20-30 people, we can provide venues for larger crowds as well (even sponsored venues, at companies, for free).

**Comment by benjamingr** [comment]
Hey sure, I'd love to volunteer to this and it's a great time for me time wise (25Sep-27Sep). If you need anything specific to set up you can contact me at my email from https://github.com/nodejs/node

**Comment by necccc** [comment]
Hi folks, we're negotiating workshops these days, and would be great if we can hopefully confirm the Code and Learn workshop. Can we help with any input right now?

**Comment by necccc** [comment]
cc @benjamingr @mcollina

**Comment by mcollina** [comment]
This is not a long way to go now! We need some more people involved if we want to organize one in Budapest.

Unfortunately I would have to pass on that, as I would like to slow a bit on my travel schedule for Q3 and Q4.

**Comment by MylesBorins** [comment]
I personally can't be there in person but could help with finding content

**Comment by ryzokuken** [comment]
I can volunteer to help out, I believe.

**Comment by necccc** [comment]
Thank you! That would be great!

**Comment by BridgeAR** [comment]
The event is already over. I am closing this therefore.
