### ISSUE TITLE
CFP: Code + Learn @ JSConf.Asia (Singapore) 2019-06-[14|15|16]

### ISSUE THREAD

**Issue by sebdeckers** [nodejs/code-and-learn#93]
Looking for any interested mentors to help organise a Code + Learn workshop at [JSConf.Asia](https://2019.jsconf.asia).

🗓 Date: 16 June 2019 1:00 PM
🌏 Location: [LASALLE College of the Arts, 1 McNally St, Singapore 187940](https://goo.gl/maps/XsyALpSmnNF2)
⏳ Duration: 3.5 hours

Ideally mentors have contributed to Node.js in some way before, and/or attended a previous Code + Learn. Local mentors: We can do a "rehearsal" C+L to familiarise ourselves with the event format.

Note: I am not an organiser of the conference; just trying to propose a C+L workshop. Any indication of support or interest is appreciated. Upvote/comment please.

/cc @fazman @serrynaimo @qiannyqian

### Participating Mentors

- @sebdeckers 
- you?
- you?
- you?
- you?
- you?
- you?

**Comment by serrynaimo** [comment]
I think topically you'd best fit on the 16th of June at 1pm. Location is the LASALLE College of the Arts at 1 McNally St.

**Comment by sebdeckers** [comment]
@serrynaimo Thanks. Updated the description.

**Comment by serrynaimo** [comment]
Would be good to keep it to 1 or maximum 2 mentors (3 including you). We don't have that much space :)

**Comment by ryzokuken** [comment]
@sebdeckers I guess it'll be much easier to volunteer once the speakers are announced? I personally submitted a couple proposals, and it'll be highly likely that any core collaborators who are selected to speak would end up also volunteering to mentor.

**Comment by Trott** [comment]
Looks like this event is now in the past so I'm going to close this. Please re-open or comment if I'm mistaken.
