### ISSUE TITLE
Code And Learn At Beijing April 28th

### ISSUE THREAD

**Issue by oyyd** [nodejs/code-and-learn#94]
Our team in [Bytedance](https://en.wikipedia.org/wiki/ByteDance) is planning to run a code & learn workshop in Beijing, China on April 28th. And we have contacted some core collaborators in China as the mentors.

[Our office](https://www.google.com/maps/place/%E5%AD%97%E8%8A%82%E8%B7%B3%E5%8A%A8%E6%80%BB%E9%83%A8/@39.9723919,116.3263186,16.06z/data=!4m5!3m4!1s0x35f053daf21a4ebd:0xc8f19e23a9ecd877!8m2!3d39.9721322!4d116.3295454) space will be used for the event and we expect there will be about 30 attendees. PRs will be submitted between 15:00 ~ 17:00 in China (UTC 7:00 ~ 9:00).

The assignments for attendees include:

- Add `mustCall()` for tests like [this one](https://github.com/nodejs/node/blob/master/test/parallel/test-net-binary.js#L37).
- [Promote v8 namespaces with using v8:: in src directory (by @ZYSzys)](https://github.com/nodejs/code-and-learn/issues/88#issuecomment-435818615).

We will concretize the assignments once the list of attendees is confirmed.

Any suggestions will be appreciated!

## Mentors

- [x] @joyeecheung
- [x] @starkwang
- [x] @yorkie
- [x] @oyyd
- [ ] @zyszys

**Comment by bugall** [comment]
nice ~

**Comment by leeight** [comment]
👍

**Comment by soyaine** [comment]
Will the workshop open the registration for others to participate in?

**Comment by oyyd** [comment]
Hi, @soyaine. You can contact me via email if you are interested in the workshop :)

**Comment by oyyd** [comment]
For now, we have about 40 attendees and the assignments we have planned are shown below:

- Add `common.mustCall()` to these functions:
  - https://github.com/nodejs/node/blob/master/test/parallel/test-net-binary.js#L37
  - https://github.com/nodejs/node/blob/master/test/parallel/test-net-after-close.js#L27
  - https://github.com/nodejs/node/blob/master/test/parallel/test-net-buffersize.js#L29
  - https://github.com/nodejs/node/blob/master/test/parallel/test-net-bytes-read.js#L9
  - https://github.com/nodejs/node/blob/master/test/parallel/test-net-bytes-stats.js#L31
  - https://github.com/nodejs/node/blob/master/test/parallel/test-net-can-reset-timeout.js#L46
  - https://github.com/nodejs/node/blob/master/test/parallel/test-net-connect-buffer.js#L36
  - https://github.com/nodejs/node/blob/master/test/parallel/test-net-connect-paused-connection.js#L27
  - https://github.com/nodejs/node/blob/master/test/parallel/test-net-dns-custom-lookup.js#L19
  - https://github.com/nodejs/node/blob/master/test/parallel/test-dgram-bytes-length.js#L35
  - https://github.com/nodejs/node/blob/master/test/parallel/test-dgram-cluster-bind-error.js#L15
  - https://github.com/nodejs/node/blob/master/test/parallel/test-dgram-connect-send-callback-buffer-length.js#L20
  - https://github.com/nodejs/node/blob/master/test/parallel/test-dgram-connect-send-callback-buffer.js#L17
  - https://github.com/nodejs/node/blob/master/test/parallel/test-dgram-connect-send-multi-buffer-copy.js#L17
  - https://github.com/nodejs/node/blob/master/test/parallel/test-dgram-connect-send-multi-string-array.js#L13
  - https://github.com/nodejs/node/blob/master/test/parallel/test-dgram-exclusive-implicit-bind.js#L72
  - https://github.com/nodejs/node/blob/master/test/parallel/test-dgram-implicit-bind.js#L39
  - https://github.com/nodejs/node/blob/master/test/parallel/test-dgram-listen-after-bind.js#L36
  - https://github.com/nodejs/node/blob/master/test/parallel/test-dgram-multicast-setTTL.js#L28
  - https://github.com/nodejs/node/blob/master/test/parallel/test-dgram-send-address-types.js#L13
  - https://github.com/nodejs/node/blob/master/test/parallel/test-fs-existssync-false.js#L34
  - https://github.com/nodejs/node/blob/master/test/parallel/test-fs-readfile-empty.js#L33
  - https://github.com/nodejs/node/blob/master/test/parallel/test-fs-readfile-pipe-large.js#L32
  - https://github.com/nodejs/node/blob/master/test/parallel/test-fs-readfile-pipe.js#L50
  - https://github.com/nodejs/node/blob/master/test/parallel/test-fs-readfile-unlink.js#L40
  - https://github.com/nodejs/node/blob/master/test/parallel/test-fs-readfilesync-pipe-large.js#L29
  - https://github.com/nodejs/node/blob/master/test/parallel/test-http-abort-client.js#L27
  - https://github.com/nodejs/node/blob/master/test/parallel/test-http-abort-queued.js#L43
- Add `common.mustCallAtLeast()` to these functions
  - https://github.com/nodejs/node/blob/master/test/parallel/test-fs-read-stream-fd.js#L38
  - https://github.com/nodejs/node/blob/master/test/parallel/test-fs-read-stream-inherit.js#L29
  - https://github.com/nodejs/node/blob/master/test/parallel/test-fs-read-stream-resume.js#L35
  - https://github.com/nodejs/node/blob/master/test/parallel/test-fs-read-stream.js#L56
  - https://github.com/nodejs/node/blob/master/test/parallel/test-fs-readfile-empty.js#L33

**Comment by oyyd** [comment]
The Code & Learn Beijing is about to start in one and a half hours from now(15:00 ~ 17:00 in China UTC 7:00 ~ 9:00). Request @nodejs/collaborators to support this with reviews and hand-holding. Thanks!

**Comment by oyyd** [comment]
The event has finished successfully! Our attendees are really glad to participate in such a workshop!

Many thanks to our mentors and their impressive talks:

- @starkwang 
- @yorkie
- @joyeecheung

And thank you collaborators for helping review and merge the PRs! (hope I didn't miss any of you :-))

- @ZYSzys
- @gireeshpunathil 
- @cjihrig 
- @Trott 
- @shisama
- @hiroppy 
- @richardlau 
- @jasnell
- @antsmartian
