### ISSUE TITLE
Code & Learn Saint Petersburg 2019

### ISSUE THREAD

**Issue by DmitryMakhnev** [nodejs/code-and-learn#95]
Hi there,

I'm a member of program committee [HolyJS Piter 2019 conference](https://holyjs-piter.ru/en/).
HolyJS and [PiterJS](https://medium.com/piterjs) (our local JS community) would like to organize Code & Learn workshop day after conference free for anybody.

@BridgeAR and @ryzokuken have been accepted to HolyJS Piter 2019 program (we'll update site as soon as possible) and also we've talked about Code & Learning a lot and they agree to help with this.
Russian community is really interesting in Node.js (we have a lot of requests for Node.js topics for the conference) and I think that Code & Learning in Saint Petersburg will be wonderful for community.

Date: May 26th, 2019
Place: Russia, Saint Petersburg

## Mentors
- [x] @BridgeAR
- [x] @ryzokuken  
- [x] @ChALkeR

**Comment by baitun** [comment]
When will registration open?

**Comment by DmitryMakhnev** [comment]
We are planning format of the registration and looking the best for place for this. News will be soon.

**Comment by ChALkeR** [comment]
Count me in =).

**Comment by DmitryMakhnev** [comment]
@ChALkeR welcome!

**Comment by DmitryMakhnev** [comment]
@baitun we are open the registration https://medium.com/piterjs/code-learn-ce20d330530f

**Comment by DmitryMakhnev** [comment]
https://twitter.com/mike1pol/status/1132998218483195904

**Comment by BridgeAR** [comment]
@DmitryMakhnev thanks a lot for organizing everything!

**Comment by DmitryMakhnev** [comment]
@BridgeAR you are welcome. I was really happy to meet you.
I hope that it isn't last Code + Learn in Russia in this year.

**Comment by ryzokuken** [comment]
*cough* Moscow *cough*
