### ISSUE TITLE
Code & Learn Moscow 2019

### ISSUE THREAD

**Issue by DmitryMakhnev** [nodejs/code-and-learn#98]
Hi there,

I'm a member of program committee HolyJS 2019 Moscow conference.
HolyJS and PiterJS (our Saint Petersburg JS community) would like to organize Code & Learn workshop 2 days before the conference free for anybody.

Russian community is really interesting in Node.js (we have a lot of requests for Node.js topics for the conference) and I think that Code & Learning in Moscow will be wonderful for community.

Date: November 6th, 2019
Place: 1-Y Nagatinskiy Proyezd, 10, building 1, floor 12, [tutu.ru](https://www.tutu.ru/) office, Moscow, Russia

## Mentors
- [x] @BridgeAR
- [x] @ryzokuken  
- [x] @ChALkeR

**Comment by ChALkeR** [comment]
Just in case: I confirm that I will be present there.

**Comment by BridgeAR** [comment]
Closing, since the event ended.
